# Generated by Django 3.2.4 on 2021-06-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='book name')),
                ('author_book', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author book')),
                ('public_year', models.CharField(max_length=50, verbose_name='Year of publication')),
                ('time_record_book', models.DateTimeField(verbose_name='Time to record books')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name')),
                ('update_time', models.DateTimeField(verbose_name='update time')),
            ],
        ),
    ]
